package org.example.model;

public enum ThreatType {
    THREAT_TYPE_UNSPECIFIED,
    MALWARE,
    SOCIAL_ENGINEERING,
    UNWANTED_SOFTWARE,
    SOCIAL_ENGINEERING_EXTENDED_COVERAGE,
    UNRECOGNIZED
}
